version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
    - path: .env
      required: true # default

  basic_api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '8000:8000'
    env_file:
    - path: .env
      required: true # default
