version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=basic_user
      - POSTGRES_DB=basic_db

  basic_api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '8000:8000'
    