apiVersion: v1
kind: Secret
metadata:
  name: front-credentials
type: Opaque
data:
  REACT_APP_AUTH0_AUDIENCE: aHR0cHM6Ly93d3cuc2t5cG91ay5vcmcvYXBp
  REACT_APP_AUTH0_DOMAIN: ZGV2LXJ1eWRyNTRucWJyN3N4YW8udXMuYXV0aDAuY29t
  REACT_APP_AUTH0_CLIENT_ID: bkxlM2E5QnRLUXRCVkE4ZmE3Nk5tbGpTT1pxTVRyMzg=
  REACT_APP_AUTH0_CALLBACK_URL: aHR0cHM6Ly93d3cuc2t5cG91ay5vcmcvY2FsbGJhY2s=
  REACT_APP_API_SERVER_URL: aHR0cHM6Ly93d3cuc2t5cG91ay5vcmc=
