apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: skypouk/basics_api:v3.0.0
          ports:
            - containerPort: 8000 # Adjust port as needed
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: back-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: back-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: back-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: AUTH0_ISSUER
              valueFrom:
                secretKeyRef:
                  name: back-credentials
                  key: AUTH0_ISSUER
            - name: CLIENT_ORIGIN_URL
              valueFrom:
                secretKeyRef:
                  name: back-credentials
                  key: CLIENT_ORIGIN_URL
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: back-credentials
                  key: AUTH0_AUDIENCE
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: back-credentials
                  key: AUTH0_DOMAIN
